Allow duplicates
AY1920S2-CS2103T-W12-4/main pull request #293
Opened 2020-04-08 12:24 UTC by e0316059

2020-04-08 13:09 UTC, kevinswk94 requested changes
Hi Mingsi, that's a interesting way of implementing it. However, now when CookBuddy is re-opened, it's forced to load from an empty recipebook since the recipebook should only contain unique recipes.

Recipes are considered identical when they have the same:
- Name
- Ingredients
- Instructions

My suggestion is to see how the ModifyCommand works and go from there.
You could append "(2)" to the recipe's name so that it will pass the unique recipe check.

2020-04-08 13:18 UTC, AdarshChugani commented
> Hi Mingsi, that's a interesting way of implementing it. However, now when CookBuddy is re-opened, it's forced to load from an empty recipebook since the recipebook should only contain unique recipes.
> 
> Recipes are considered identical when they have the same:
> 
> * Name
> * Ingredients
> * Instructions
> 
> My suggestion is to see how the ModifyCommand works and go from there.
> You could append "(2)" to the recipe's name so that it will pass the unique recipe check.

Just to add on, you could consider appending "Copy of " or "Duplicate of " at the start

2020-04-09 10:10 UTC, e0316059 commented
> Hi Mingsi, that's a interesting way of implementing it. However, now when CookBuddy is re-opened, it's forced to load from an empty recipebook since the recipebook should only contain unique recipes.
> 
> Recipes are considered identical when they have the same:
> 
> * Name
> * Ingredients
> * Instructions
> 
> My suggestion is to see how the ModifyCommand works and go from there.
> You could append "(2)" to the recipe's name so that it will pass the unique recipe check.

Thanks! I've change it to "duplicate of ...." as adarsh suggested

2020-04-09 11:25 UTC, kevinswk94 approved these changes

2020-04-09 12:23 UTC, merged